#!/usr/bin/env bash

VOLUME_STEP=5

get_volume() {
    pulsemixer --get-volume | awk '{print ($1 > $2) ? $1 : $2}'
}

get_mute() {
    pulsemixer --get-mute
}

increase(){ 
    local step="${1:-$VOLUME_STEP}"
    if [[ "$(get_mute)" -eq 1 ]]; then
       unmute 
    fi
    pulsemixer --change-volume +"$step"
}

decrease(){ 
    local step="${1:-$VOLUME_STEP}"
    if [[ "$(get_mute)" -eq 1 ]]; then
       unmute 
    fi
    pulsemixer --change-volume -"$step"
}

mute() {
    pulsemixer --mute
}

unmute() {
    pulsemixer --unmute
}

toggle() {
    if [[ "$(get_mute)" -eq 1 ]]; then
        unmute
    else
        mute
    fi
}

if command -v pulsemixer >/dev/null; then
    case "$1" in
        --get-volume)
            get_volume
            ;;
        --increase)
            increase "$2"
            ;;
        --decrease) 
            decrease "$2"
            ;;
        --get-mute)
            get_mute
            ;;
        --mute)
            mute
            ;;
        --unmute)
            unmute
            ;;
        --toggle)
            toggle
            ;;
    esac
else
    echo "pulsemixer not found"
    exit 1
fi
